import json
import os

notebook = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# Object Detection and Semantic Segmentation using Oxford-IIIT Pet Dataset\n",
                "## YOLOv11 vs U-Net\n",
                "This notebook implements and compares YOLOv11 for object detection and U-Net for semantic segmentation. Designed for execution in Google Colab."
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 1. Setup Environment"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!pip install -q ultralytics kagglehub\n",
                "import kagglehub\n",
                "import os\n",
                "import shutil\n",
                "import xml.etree.ElementTree as ET\n",
                "import cv2\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import torch\n",
                "import torch.nn as nn\n",
                "import torch.optim as optim\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "import torchvision.transforms as transforms\n",
                "from PIL import Image\n",
                "from sklearn.model_selection import train_test_split\n",
                "from ultralytics import YOLO\n",
                "import glob\n",
                "from tqdm import tqdm\n",
                "import time"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 2. Download and Extract Data"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Download latest version of Oxford-IIIT Pet dataset\n",
                "path = kagglehub.dataset_download(\"tanlikesmath/the-oxfordiiit-pet-dataset\")\n",
                "print(\"Path to dataset files:\", path)\n",
                "\n",
                "dataset_dir = './dataset'\n",
                "if not os.path.exists(dataset_dir):\n",
                "    shutil.copytree(path, dataset_dir)\n",
                "print(\"Data copied to\", dataset_dir)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 3. Data Preprocessing (Train/Val/Test Split & YOLO format)"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "images_dir = os.path.join(dataset_dir, 'images/images')\n",
                "annotations_dir = os.path.join(dataset_dir, 'annotations/annotations/xmls')\n",
                "trimaps_dir = os.path.join(dataset_dir, 'annotations/annotations/trimaps')\n",
                "\n",
                "# Get list of valid images that have annotations\n",
                "all_images = [f for f in os.listdir(images_dir) if f.endswith('.jpg')]\n",
                "valid_samples = []\n",
                "\n",
                "for img_name in tqdm(all_images, desc=\"Checking annotations\"):\n",
                "    base_name = os.path.splitext(img_name)[0]\n",
                "    xml_path = os.path.join(annotations_dir, f\"{base_name}.xml\")\n",
                "    trimap_path = os.path.join(trimaps_dir, f\"{base_name}.png\")\n",
                "    if os.path.exists(xml_path) and os.path.exists(trimap_path):\n",
                "        valid_samples.append(base_name)\n",
                "\n",
                "print(f\"Total valid samples: {len(valid_samples)}\")\n",
                "\n",
                "# Train/Val/Test Split (70/15/15)\n",
                "train_samples, temp_samples = train_test_split(valid_samples, test_size=0.3, random_state=42)\n",
                "val_samples, test_samples = train_test_split(temp_samples, test_size=0.5, random_state=42)\n",
                "\n",
                "print(f\"Train: {len(train_samples)}, Val: {len(val_samples)}, Test: {len(test_samples)}\")\n",
                "\n",
                "# Create YOLO directories\n",
                "yolo_base_dir = './yolo_data'\n",
                "for split in ['train', 'val', 'test']:\n",
                "    os.makedirs(os.path.join(yolo_base_dir, 'images', split), exist_ok=True)\n",
                "    os.makedirs(os.path.join(yolo_base_dir, 'labels', split), exist_ok=True)\n",
                "\n",
                "# Parse XML to YOLO\n",
                "def convert_xml_to_yolo(xml_path):\n",
                "    tree = ET.parse(xml_path)\n",
                "    root = tree.getroot()\n",
                "    size = root.find('size')\n",
                "    w = int(size.find('width').text)\n",
                "    h = int(size.find('height').text)\n",
                "    \n",
                "    bndbox = root.find('object').find('bndbox')\n",
                "    xmin = float(bndbox.find('xmin').text)\n",
                "    ymin = float(bndbox.find('ymin').text)\n",
                "    xmax = float(bndbox.find('xmax').text)\n",
                "    ymax = float(bndbox.find('ymax').text)\n",
                "    \n",
                "    x_center = ((xmin + xmax) / 2) / w\n",
                "    y_center = ((ymin + ymax) / 2) / h\n",
                "    width = (xmax - xmin) / w\n",
                "    height = (ymax - ymin) / h\n",
                "    \n",
                "    return [0, x_center, y_center, width, height]  # Class 0: Pet\n",
                "\n",
                "for split_name, split_list in zip(['train', 'val', 'test'], [train_samples, val_samples, test_samples]):\n",
                "    for base_name in tqdm(split_list, desc=f\"Processing {split_name} data\"):\n",
                "        xml_path = os.path.join(annotations_dir, f\"{base_name}.xml\")\n",
                "        try:\n",
                "            yolo_anno = convert_xml_to_yolo(xml_path)\n",
                "            \n",
                "            src_img = os.path.join(images_dir, f\"{base_name}.jpg\")\n",
                "            dst_img = os.path.join(yolo_base_dir, 'images', split_name, f\"{base_name}.jpg\")\n",
                "            shutil.copy(src_img, dst_img)\n",
                "            \n",
                "            label_path = os.path.join(yolo_base_dir, 'labels', split_name, f\"{base_name}.txt\")\n",
                "            with open(label_path, 'w') as f:\n",
                "                f.write(f\"{yolo_anno[0]} {yolo_anno[1]:.6f} {yolo_anno[2]:.6f} {yolo_anno[3]:.6f} {yolo_anno[4]:.6f}\\n\")\n",
                "        except Exception as e:\n",
                "            pass # Skip sample entirely to avoid empty labels\n",
                "\n",
                "yaml_content = f\"\"\"\n",
                "path: {os.path.abspath(yolo_base_dir)}\n",
                "train: images/train\n",
                "val: images/val\n",
                "test: images/test\n",
                "nc: 1\n",
                "names: ['pet']\n",
                "\"\"\"\n",
                "with open('dataset.yaml', 'w') as f:\n",
                "    f.write(yaml_content)\n",
                "print(\"YOLO dataset prepared.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 4. YOLOv11 Training and Evaluation"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "model = YOLO('yolo11n.pt')\n",
                "\n",
                "results = model.train(\n",
                "    data='dataset.yaml',\n",
                "    epochs=10, \n",
                "    imgsz=640,\n",
                "    batch=16,\n",
                "    name='pet_yolo_model'\n",
                ")\n",
                "\n",
                "metrics = model.val()\n",
                "print(\"\\n--- YOLOv11 Evaluation Metrics ---\")\n",
                "print(f\"Precision: {metrics.box.mp:.4f}\")\n",
                "print(f\"Recall:    {metrics.box.mr:.4f}\")\n",
                "print(f\"mAP50:     {metrics.box.map50:.4f}\")\n",
                "print(f\"mAP50-95:  {metrics.box.map:.4f}\\n\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 5. U-Net Architecture Definition"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class DoubleConv(nn.Module):\n",
                "    def __init__(self, in_channels, out_channels):\n",
                "        super(DoubleConv, self).__init__()\n",
                "        self.conv = nn.Sequential(\n",
                "            nn.Conv2d(in_channels, out_channels, 3, 1, 1, bias=False),\n",
                "            nn.BatchNorm2d(out_channels),\n",
                "            nn.ReLU(inplace=True),\n",
                "            nn.Conv2d(out_channels, out_channels, 3, 1, 1, bias=False),\n",
                "            nn.BatchNorm2d(out_channels),\n",
                "            nn.ReLU(inplace=True),\n",
                "        )\n",
                "\n",
                "    def forward(self, x):\n",
                "        return self.conv(x)\n",
                "\n",
                "class UNet(nn.Module):\n",
                "    def __init__(self, in_channels=3, out_channels=1, features=[64, 128, 256, 512]):\n",
                "        super(UNet, self).__init__()\n",
                "        self.ups = nn.ModuleList()\n",
                "        self.downs = nn.ModuleList()\n",
                "        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)\n",
                "\n",
                "        for feature in features:\n",
                "            self.downs.append(DoubleConv(in_channels, feature))\n",
                "            in_channels = feature\n",
                "\n",
                "        for feature in reversed(features):\n",
                "            self.ups.append(\n",
                "                nn.ConvTranspose2d(feature*2, feature, kernel_size=2, stride=2)\n",
                "            )\n",
                "            self.ups.append(DoubleConv(feature*2, feature))\n",
                "\n",
                "        self.bottleneck = DoubleConv(features[-1], features[-1]*2)\n",
                "        self.final_conv = nn.Conv2d(features[0], out_channels, kernel_size=1)\n",
                "\n",
                "    def forward(self, x):\n",
                "        skip_connections = []\n",
                "        for down in self.downs:\n",
                "            x = down(x)\n",
                "            skip_connections.append(x)\n",
                "            x = self.pool(x)\n",
                "\n",
                "        x = self.bottleneck(x)\n",
                "        skip_connections = skip_connections[::-1]\n",
                "\n",
                "        for idx in range(0, len(self.ups), 2):\n",
                "            x = self.ups[idx](x)\n",
                "            skip_connection = skip_connections[idx//2]\n",
                "\n",
                "            if x.shape != skip_connection.shape:\n",
                "                x = transforms.functional.resize(x, size=skip_connection.shape[2:])\n",
                "\n",
                "            concat_skip = torch.cat((skip_connection, x), dim=1)\n",
                "            x = self.ups[idx+1](concat_skip)\n",
                "\n",
                "        return self.final_conv(x)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 6. U-Net Data Loading and Training"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "class PetDataset(Dataset):\n",
                "    def __init__(self, sample_list, images_dir, trimaps_dir, transform=None):\n",
                "        self.sample_list = sample_list\n",
                "        self.images_dir = images_dir\n",
                "        self.trimaps_dir = trimaps_dir\n",
                "        self.transform = transform\n",
                "\n",
                "    def __len__(self):\n",
                "        return len(self.sample_list)\n",
                "\n",
                "    def __getitem__(self, idx):\n",
                "        base_name = self.sample_list[idx]\n",
                "        img_path = os.path.join(self.images_dir, f\"{base_name}.jpg\")\n",
                "        mask_path = os.path.join(self.trimaps_dir, f\"{base_name}.png\")\n",
                "\n",
                "        image = Image.open(img_path).convert(\"RGB\")\n",
                "        mask = Image.open(mask_path)\n",
                "        mask = np.array(mask)\n",
                "        binary_mask = (mask == 1).astype(np.float32)\n",
                "\n",
                "        if self.transform:\n",
                "            image = self.transform(image)\n",
                "            mask = transforms.functional.to_tensor(binary_mask)\n",
                "            mask = transforms.functional.resize(mask, size=(128, 128), interpolation=transforms.InterpolationMode.NEAREST)\n",
                "\n",
                "        return image, mask\n",
                "\n",
                "transform = transforms.Compose([\n",
                "    transforms.Resize((128, 128)),\n",
                "    transforms.ToTensor(),\n",
                "    transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])\n",
                "])\n",
                "\n",
                "train_dataset = PetDataset(train_samples, images_dir, trimaps_dir, transform)\n",
                "val_dataset = PetDataset(val_samples, images_dir, trimaps_dir, transform)\n",
                "\n",
                "train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)\n",
                "val_loader = DataLoader(val_dataset, batch_size=16, shuffle=False)\n",
                "\n",
                "def dice_loss(pred, target, smooth=1.):\n",
                "    pred = torch.sigmoid(pred)\n",
                "    intersection = (pred * target).sum()\n",
                "    return 1 - ((2. * intersection + smooth) / (pred.sum() + target.sum() + smooth))\n",
                "\n",
                "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
                "model_unet = UNet(in_channels=3, out_channels=1).to(device)\n",
                "optimizer = optim.Adam(model_unet.parameters(), lr=1e-4)\n",
                "bce_fn = nn.BCEWithLogitsLoss()\n",
                "\n",
                "num_epochs = 15\n",
                "train_losses = []\n",
                "val_losses = []\n",
                "best_val_loss = float('inf')\n",
                "\n",
                "for epoch in range(num_epochs):\n",
                "    # Training Phase\n",
                "    model_unet.train()\n",
                "    loop = tqdm(train_loader, desc=f\"Epoch {epoch+1}/{num_epochs} [Train]\")\n",
                "    epoch_train_loss = 0\n",
                "    for batch_idx, (data, targets) in enumerate(loop):\n",
                "        data = data.to(device)\n",
                "        targets = targets.to(device)\n",
                "        \n",
                "        predictions = model_unet(data)\n",
                "        loss = bce_fn(predictions, targets) + dice_loss(predictions, targets)\n",
                "        \n",
                "        optimizer.zero_grad()\n",
                "        loss.backward()\n",
                "        optimizer.step()\n",
                "        \n",
                "        epoch_train_loss += loss.item()\n",
                "        loop.set_postfix(loss=loss.item())\n",
                "        \n",
                "    avg_train_loss = epoch_train_loss / len(train_loader)\n",
                "    train_losses.append(avg_train_loss)\n",
                "    \n",
                "    # Validation Phase\n",
                "    model_unet.eval()\n",
                "    epoch_val_loss = 0\n",
                "    with torch.no_grad():\n",
                "        val_loop = tqdm(val_loader, desc=f\"Epoch {epoch+1}/{num_epochs} [Val]\")\n",
                "        for data, targets in val_loop:\n",
                "            data = data.to(device)\n",
                "            targets = targets.to(device)\n",
                "            \n",
                "            predictions = model_unet(data)\n",
                "            loss = bce_fn(predictions, targets) + dice_loss(predictions, targets)\n",
                "            epoch_val_loss += loss.item()\n",
                "            \n",
                "    avg_val_loss = epoch_val_loss / len(val_loader)\n",
                "    val_losses.append(avg_val_loss)\n",
                "    print(f\"Epoch {epoch+1} - Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}\")\n",
                "    \n",
                "    # Save Best Model\n",
                "    if avg_val_loss < best_val_loss:\n",
                "        best_val_loss = avg_val_loss\n",
                "        torch.save(model_unet.state_dict(), 'best_unet.pth')\n",
                "        print(\"--> Saved new best model!\")\n",
                "\n",
                "print(\"U-Net training complete.\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 7. Evaluation & Metrics"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Plot Training Curves\n",
                "plt.figure(figsize=(10, 5))\n",
                "plt.plot(range(1, num_epochs+1), train_losses, label='Train Loss')\n",
                "plt.plot(range(1, num_epochs+1), val_losses, label='Validation Loss')\n",
                "plt.xlabel('Epochs')\n",
                "plt.ylabel('Loss (BCE + Dice)')\n",
                "plt.title('U-Net Training and Validation Loss')\n",
                "plt.legend()\n",
                "plt.grid(True)\n",
                "plt.show()\n",
                "\n",
                "# Load best U-Net model\n",
                "model_unet.load_state_dict(torch.load('best_unet.pth'))\n",
                "\n",
                "test_dataset = PetDataset(test_samples, images_dir, trimaps_dir, transform)\n",
                "test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False)\n",
                "\n",
                "def compute_unet_metrics(loader, model, device):\n",
                "    total_iou = 0\n",
                "    total_dice = 0\n",
                "    total_pixel_acc = 0\n",
                "    total_precision = 0\n",
                "    total_recall = 0\n",
                "    \n",
                "    model.eval()\n",
                "    with torch.no_grad():\n",
                "        for data, targets in tqdm(loader, desc=\"Evaluating U-Net\"):\n",
                "            data = data.to(device)\n",
                "            targets = targets.to(device)\n",
                "            \n",
                "            preds = torch.sigmoid(model(data))\n",
                "            preds = (preds > 0.5).float()\n",
                "            \n",
                "            preds_flat = preds.view(-1)\n",
                "            targets_flat = targets.view(-1)\n",
                "            \n",
                "            intersection = (preds_flat * targets_flat).sum()\n",
                "            union = preds_flat.sum() + targets_flat.sum() - intersection\n",
                "            \n",
                "            iou = (intersection + 1e-6) / (union + 1e-6)\n",
                "            total_iou += iou.item()\n",
                "            \n",
                "            dice = (2. * intersection + 1e-6) / (preds_flat.sum() + targets_flat.sum() + 1e-6)\n",
                "            total_dice += dice.item()\n",
                "            \n",
                "            pixel_acc = (preds_flat == targets_flat).float().mean()\n",
                "            total_pixel_acc += pixel_acc.item()\n",
                "            \n",
                "            true_positives = intersection\n",
                "            false_positives = (preds_flat * (1 - targets_flat)).sum()\n",
                "            false_negatives = ((1 - preds_flat) * targets_flat).sum()\n",
                "            \n",
                "            precision = (true_positives + 1e-6) / (true_positives + false_positives + 1e-6)\n",
                "            recall = (true_positives + 1e-6) / (true_positives + false_negatives + 1e-6)\n",
                "            \n",
                "            total_precision += precision.item()\n",
                "            total_recall += recall.item()\n",
                "            \n",
                "    n = len(loader)\n",
                "    print(\"\\n--- U-Net Evaluation Metrics ---\")\n",
                "    print(f\"Pixel Accuracy: {total_pixel_acc/n:.4f}\")\n",
                "    print(f\"Precision:      {total_precision/n:.4f}\")\n",
                "    print(f\"Recall:         {total_recall/n:.4f}\")\n",
                "    print(f\"IoU:            {total_iou/n:.4f}\")\n",
                "    print(f\"Dice Score:     {total_dice/n:.4f}\\n\")\n",
                "\n",
                "compute_unet_metrics(test_loader, model_unet, device)"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 8. Inference Speed Comparison"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "print(\"\\n--- Inference Speed Comparison ---\")\n",
                "sample_img_path = os.path.join(images_dir, f\"{test_samples[0]}.jpg\")\n",
                "\n",
                "# YOLO Inference Speed\n",
                "start_yolo = time.time()\n",
                "yolo_res = model.predict(sample_img_path, imgsz=640, verbose=False)\n",
                "end_yolo = time.time()\n",
                "yolo_time = (end_yolo - start_yolo) * 1000 # in ms\n",
                "\n",
                "# U-Net Inference Speed\n",
                "image = Image.open(sample_img_path).convert(\"RGB\")\n",
                "input_tensor = transform(image).unsqueeze(0).to(device)\n",
                "start_unet = time.time()\n",
                "with torch.no_grad():\n",
                "    _ = model_unet(input_tensor)\n",
                "end_unet = time.time()\n",
                "unet_time = (end_unet - start_unet) * 1000 # in ms\n",
                "\n",
                "print(f\"YOLOv11 Inference Time: {yolo_time:.2f} ms\")\n",
                "print(f\"U-Net Inference Time:   {unet_time:.2f} ms\\n\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "### 9. Side-by-Side Visual Comparison"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "def unnormalize(tensor):\n",
                "    mean = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)\n",
                "    std = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)\n",
                "    return tensor * std + mean\n",
                "\n",
                "model_unet.eval()\n",
                "\n",
                "num_samples = 3\n",
                "fig, axes = plt.subplots(num_samples, 3, figsize=(15, 5*num_samples))\n",
                "\n",
                "for i in range(num_samples):\n",
                "    base_name = test_samples[i]\n",
                "    img_path = os.path.join(images_dir, f\"{base_name}.jpg\")\n",
                "    \n",
                "    # YOLO Inference\n",
                "    yolo_res = model.predict(img_path, imgsz=640, verbose=False)\n",
                "    yolo_img = yolo_res[0].plot()\n",
                "    \n",
                "    # U-Net Inference\n",
                "    image = Image.open(img_path).convert(\"RGB\")\n",
                "    input_tensor = transform(image).unsqueeze(0).to(device)\n",
                "    with torch.no_grad():\n",
                "        preds = torch.sigmoid(model_unet(input_tensor))\n",
                "        preds = (preds > 0.5).float()\n",
                "    \n",
                "    orig_img = unnormalize(input_tensor.squeeze(0).cpu()).permute(1, 2, 0).numpy()\n",
                "    orig_img = np.clip(orig_img, 0, 1)\n",
                "    mask_img = preds.squeeze(0).squeeze(0).cpu().numpy()\n",
                "    \n",
                "    axes[i, 0].imshow(np.array(Image.open(img_path)))\n",
                "    axes[i, 0].set_title(\"Original Image\")\n",
                "    axes[i, 0].axis('off')\n",
                "    \n",
                "    axes[i, 1].imshow(yolo_img[..., ::-1])\n",
                "    axes[i, 1].set_title(\"YOLOv11 Detection\")\n",
                "    axes[i, 1].axis('off')\n",
                "    \n",
                "    axes[i, 2].imshow(orig_img)\n",
                "    axes[i, 2].imshow(mask_img, alpha=0.5, cmap='jet')\n",
                "    axes[i, 2].set_title(\"U-Net Segmentation Mask\")\n",
                "    axes[i, 2].axis('off')\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "name": "python",
            "version": "3.10"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

with open("d:/College/yolo/Oxford_Pet_YOLO_UNet.ipynb", "w") as f:
    json.dump(notebook, f, indent=4)

print("Successfully generated Oxford_Pet_YOLO_UNet.ipynb!")
